@startuml
class VideregåendeUddannelse {}
class Fagområde {}
class UddannelsesansvarligEnhed {}
class Censorkorps {}
class Uddannelse {}
class UddannelsesansvarligPerson {}
class Udbudssted {}
class OrgEnhed {}
class OrgPerson {}
class Uddannelsesinstitution {}
class Person {}
class DanskAdresse {}
class Adresse {}
class GodkendtUdbudssted {}
class Universitet {}
class Organisation {}
class Statsborgerskab {}
class UdenlandskAdresse {}
class Ansat {}
class PersonUdenCpr {}
class GeneriskPerson {}
class CprAdresse {}
class Ansøger {}
class Medlemskab {}
class InstitutionsRegister {}
class RegisterRegistrering {}
class DanskInstitutionsRegisterRegistrering {}
class Studieordning {}
class Studieforløb {}
class Studieordningsregel {}
class DiplomaSupplement {}
class Studieforløbsperiode {}
class AdgangsgivendeUddannelse {}
class Forløbsprøve {}
class Fagelement {}
class Fagelementemne {}
class FagelementansvarligEnhed {}
class FagelementansvarligPerson {}
class ÆkvivalerendeFaglighed {}
class OverlappendeFaglighed {}
class GrupperingAfFagelement {}
class FagelementIFagelementgruppering {}
class UdbudtLæringsaktivitet {}
class UdbudtUndervisning {}
class UdbudtFagligVejledning {}
class UdbudtPraktikophold {}
class UdbudtProjektarbejde {}
class UdbudtProjektorienteretOphold {}
class Samlæsning {}
class UdbudtLæringsaktivitetsansvarligPerson {}
class Prøve {}
class Prøvevariant {}
class Prøveemne {}
class Prøvebegivenhed {}
class Prøveaktivitet {}
class Eksamensforudsætning {}
class Godkendelsesaktivitet {}
class UdbudtVideregåendeUddannelse {}
class UdbudtVideregåendeUddannelseOgEnkeltfag {}
class Optagelsesperiode {}
class Udbudshjemmel {}
class Bogføringsoplysninger {}
class Pris {}
class Ansøgningsfrist {}
class Studiestart {}
class UdbudtStudieforløb {}
class Holdbegivenhed {}
class Holdønske {}
class Hold {}
class HoldBegivenhedPerson {}
class UdbudtFagelement {}
class Skemagruppe {}
class UdbudtFagelementansvarligEnhed {}
class UdbudtFagelementansvarligPerson {}
class TilmeldingTilUdbudtFagelement {}
class FrameldingFraUdbudtFagelement {}
class Aftalegrundlag {}
class TilmeldingTilUdbudtLæringsaktivitet {}
class Adgangsgrundlag {}
class Indskrivning {}
class IndskrivningTilEnkeltfag {}
class IndskrivningTilVideregåendeUddannelse {}
class AdgangsgivendeErhvervserfaring {}
class Studerende {}
class EuropeanStudentIdentifier {}
class UdbudtPrøvevariant {}
class UdbudtPrøvebegivenhed {}
class Sameksamination {}
class UdbudtPrøveaktivitet {}
class UdbudtPrøve {}
class TidOgSted {}
class UdbudtEksamensforudsætning {}
class UdbudtEksamensforudsætningTilknytning {}
class Prøvetilmelding {}
class FrameldingFraUdbudtPrøveaktivitet {}
class Eksamensgruppe {}
class Prøveaktivitetstilmelding {}
class PersonligPrøvebegivenhed {}
class TIlmeldingTilEksamensforudsætning {}
class UdbudtEnkeltfagSomTomplads {}
@enduml
